### PR TITLE
Various minor doc fixes

### PR DESCRIPTION
**Pull request by ganto**

### CODE REVIEW

**Comment by ganto** [comment]
@drybjed or @ypid: Any idea why the vim markers are displayed for some default variables. See:
- [roundcube__custom_php_packages](https://debops-contrib.readthedocs.io/en/latest/ansible/roles/ansible-roundcube/docs/defaults.html#envvar-roundcube__custom_php_packages)
- [roundcube__group](https://debops-contrib.readthedocs.io/en/latest/ansible/roles/ansible-roundcube/docs/defaults.html#envvar-roundcube__group)

**Comment by drybjed** [comment]
Sorry, no idea. Perhaps you could check `yaml2rst` output by hand?

**Comment by ypid** [comment]
@ganto yaml4rst should have fixed it for you (I just tried it and it fixed it). Can you run `debops-optimize` over it?

**Comment by ganto** [comment]
If I understand @ypid correctly, this is something that should have been fixed by yaml4rst

If you're ok, I would merge this PR then you can re-generate the docs and see if its gone.

**Comment by ypid** [comment]
@ganto Did you run `yaml4rst`? When I did yesterday it fixed the spacing for the closing Vim folds for the two vars you mentioned have the issue. I still miss this change in this PR so the docs will not be fixed by merging this yet. Is there any issue with yaml4rst? btw. you could generate the docs locally using [sphinx-debops-role-build](https://github.com/ypid/ypid-ansible-common/blob/master/bin/sphinx-debops-role-build).

**Comment by ganto** [comment]
> @ganto Did you run yaml4rst?

Obviously not. Sorry, i confused `yaml4rst` with `yaml2rst` that's why I had the impression I don't have anything to do 😉 

Unfortunately I now have the next issue (see ypid/yaml4rst#2).

**Comment by ypid** [comment]
> Obviously not. Sorry, i confused yaml4rst with yaml2rst that's why I had the impression I don't have anything to do 😉

I thought the naming (4 instead of 2) was clever, maybe not :) If you have a nice idea you can open an issue or so. I am always open for improvements.

**Review by ypid — APPROVED** [review]
I only had a peek at the changes but it looks good to me. That should fix the docs issues.

**Comment by ganto** [comment]
@ypid: Thanks a lot for your support. Can you please re-generate the docs again?

**Comment by ypid** [comment]
You are welcome. [Done](https://debops-contrib.readthedocs.io/en/latest/ansible/roles/ansible-roundcube/docs/defaults.html#envvar-roundcube__custom_php_packages), looks good now :)

**Pull request merged**
